name: ci

on:
  pull_request:
  workflow_call:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
      - run: nix build --print-build-logs

  windows:
    runs-on: windows-latest
    env:
      # Fix for hanging builds
      MSBUILDDISABLENODEREUSE: 1
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "10.0.x"

      - name: Install jujutsu
        shell: pwsh
        run: |
          $ver = "0.43.0"
          $url = "https://github.com/jj-vcs/jj/releases/download/v$ver/jj-v$ver-x86_64-pc-windows-msvc.zip"
          Invoke-WebRequest $url -OutFile jj.zip
          Expand-Archive jj.zip -DestinationPath $env:RUNNER_TEMP\jj
          Add-Content $env:GITHUB_PATH "$env:RUNNER_TEMP\jj"

      - name: Run unit tests
        run: dotnet test Mutannot.UnitTests/Mutannot.UnitTests.fsproj -c Release

      - name: Run integration tests
        run: dotnet test Mutannot.IntegrationTests/Mutannot.IntegrationTests.fsproj -c Release

      - name: Run example F# tests
        run: dotnet test Example.FSharp.Tests/Example.FSharp.Tests.fsproj -c Release

      - name: Run example C# tests
        run: dotnet test Example.CSharp.Tests/Example.CSharp.Tests.csproj -c Release

      - name: Run mutannot on the example F# project
        run: dotnet run --project Mutannot/Mutannot.fsproj -c Release -- run Example.FSharp.Tests/Example.FSharp.Tests.fsproj --jobs 4

      - name: Run mutannot on the example C# project
        run: dotnet run --project Mutannot/Mutannot.fsproj -c Release -- run Example.CSharp.Tests/Example.CSharp.Tests.csproj --jobs 4

      - name: Run mutannot on itself
        run: dotnet run --project Mutannot/Mutannot.fsproj -c Release -- run Mutannot.IntegrationTests/Mutannot.IntegrationTests.fsproj --jobs 4
